### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by qwearchangel** [RequiDev/ClearVRAM#1]
This no longer work on latest 4.0 Melonloader or VRChat 1108.

**Comment by RequiDev** [comment]
The most recent VRChat update introduced better memory management:
https://docs.vrchat.com/docs/latest-release#changes-fixes-and-improvements

> Avatars that are no longer in use in the instance will be periodically unloaded from memory

Of course, I also tested this and in the following screenshot, you can see the results. I don't think this mod is necessary anymore.

![IGHYs](https://user-images.githubusercontent.com/7763240/122675001-d2382200-d1d7-11eb-8b1f-cc63cd72454d.png)

**Comment by qwearchangel** [comment]
In normal worlds: Yes, The normal VRChat ClearVRAM isnt needed. Rarely used it in normal worlds either

In big party 40+ worlds: Now we are talking a lot of loading, some ppl are assholes and is changing avatars (Most resource heavy e-boys). Also sometimes crashes when you do 1 safety change too much without clearing VRAM before you do it in latest VRChat.

I really liked this mod. It allowed me to get away with loading stuff. But ultimately, its your choice if you see any need for this mod or not and i will thank you for the work you did before the latest VRChat patch

**Comment by RequiDev** [comment]
If you think it's still useful I can update it. I already have a working copy on my end due to testing things.

**Comment by RequiDev** [comment]
https://github.com/RequiDev/ClearVRAM/releases/tag/v1.0.4
